info:
  title: ChlorineC's Blog
  author: ChlorineC

defaults:
  favicon: /images/favicon.ico
  logo: 
  avatar: /images/avatar.jpg

global:
  chinese:
    enable: true
    family: Noto Sans SC
    url: https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@400;500;700&display=swap
  busuanzi_counter:
    enable: false
    site_pv: false
    site_uv: false
    post_pv: false
  scroll_progress: 
    bar: false
    percentage: false


home_banner:
  title: Hello, World!
  subtitle:
    text: ["Stay Hungry, Stay Foolish.", "Keep Your Curiosity."]
  social_links:
    enable: true
    links: 
      github: https://github.com/KiritoKing
      zhihu: https://www.zhihu.com/people/kirito-38
      bilibili: https://space.bilibili.com/8408315
  
navbar:
  auto_hide: true
  links:
    文章:
      icon: fa-solid fa-newspaper
      submenus:
        分类: /categories/
        标签: /tags/
        归档: /archives/
    简历:
      icon: fa-solid fa-address-card
      path: /resume
    友链:
      icon: fa-solid fa-link
      path: /links/
    Github:
      path: https://www.github.com/KiritoKing
      icon: fa-brands fa-github
  search:
    enable: true

home:
  sidebar:
    annoucement:
    links:
      归档:
        icon: fa-regular fa-archive
        path: /archives/
      标签:
        icon: fa-regular fa-tags
        path: /tags
      分类:
        path: /categories # 路径
        icon: fa-regular fa-folder # 图标，可以为空

articles:
  code_block:
    style: simple

comment:
  enable: true
  system: gitalk
  config:
    gitalk:
      clientID: ff01280298235e34dda1
      clientSecret: 415ade8511f1e170013904e34eec79fa4820318e
      repo: blog-gitalk
      owner: KiritoKing

footer:
  runtime: false
  start: 2023/04/17 14:44:44
  icp:
    enable: true
    number: 蜀ICP备2022029268号
  